// Copyright (c) 2026 just_image contributors.
// SPDX-License-Identifier: MIT
// Generated by package:ffigen. Do not edit manually.
// Regenerate with: dart run tool/ffigen.dart

// ignore_for_file: type=lint, camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// Mapping from Dart function name to native symbol name.
const recordUseMapping = {
  'rust_abi_version': 'rust_abi_version',
  'rust_available_filters': 'rust_available_filters',
  'rust_blurhash_decode': 'rust_blurhash_decode',
  'rust_blurhash_encode': 'rust_blurhash_encode',
  'rust_free_buffer': 'rust_free_buffer',
  'rust_free_error': 'rust_free_error',
  'rust_free_string': 'rust_free_string',
  'rust_image_info': 'rust_image_info',
  'rust_process_core_pipeline': 'rust_process_core_pipeline',
  'rust_process_extended_pipeline': 'rust_process_extended_pipeline',
  'rust_process_pipeline': 'rust_process_pipeline',
  'rust_version': 'rust_version',
};
