// Copyright (c) 2026 just_image contributors.
// SPDX-License-Identifier: MIT

import 'dart:io';

import 'package:ffigen/ffigen.dart';

void main() {
  final packageRoot = Platform.script.resolve('../');
  final header = packageRoot.resolve('src/native/include/just_image.h');
  final bindings = packageRoot.resolve('lib/src/native_bindings.g.dart');

  const functions = {
    'rust_abi_version',
    'rust_process_pipeline',
    'rust_free_buffer',
    'rust_free_error',
    'rust_version',
    'rust_free_string',
    'rust_image_info',
    'rust_blurhash_encode',
    'rust_blurhash_decode',
    'rust_available_filters',
  };

  FfiGenerator(
    headers: Headers(entryPoints: [header]),
    functions: Functions(
      include: (declaration) => functions.contains(declaration.originalName),
      isLeaf: (declaration) =>
          declaration.originalName.startsWith('rust_free_') ||
          declaration.originalName == 'rust_abi_version',
    ),
    structs: Structs.includeSet({'FfiResult'}),
    output: Output(
      dartFile: bindings,
      style: const NativeExternalBindings(
        assetId: 'package:just_image/src/native_bindings.g.dart',
      ),
      preamble: '''
// Copyright (c) 2026 just_image contributors.
// SPDX-License-Identifier: MIT
// Generated by package:ffigen. Do not edit manually.
// Regenerate with: dart run tool/ffigen.dart

// ignore_for_file: type=lint, camel_case_types, non_constant_identifier_names
''',
    ),
  ).generate();
}
