// Copyright (c) 2026 just_image contributors.
// SPDX-License-Identifier: MIT

import 'dart:io';

import 'package:crypto/crypto.dart';

const _expectedArtifacts = <String>[
  'libjust_image_native-macos-arm64.dylib',
  'libjust_image_native-macos-x64.dylib',
  'libjust_image_native-ios-arm64.dylib',
  'libjust_image_native-ios-simulator-arm64.dylib',
  'libjust_image_native-ios-simulator-x64.dylib',
  'libjust_image_native-linux-x64.so',
  'libjust_image_native-linux-arm64.so',
  'just_image_native-windows-x64.dll',
  'just_image_native-windows-arm64.dll',
  'libjust_image_native-android-arm64.so',
  'libjust_image_native-android-arm.so',
  'libjust_image_native-android-x64.so',
];

Future<void> main(List<String> arguments) async {
  if (arguments.length != 2) {
    stderr.writeln('Usage: dart run tool/generate_hashes.dart <dir> <version>');
    exitCode = 64;
    return;
  }

  final root = Directory(arguments[0]);
  final version = arguments[1];
  final files = await root
      .list(recursive: true)
      .where((entity) => entity is File)
      .cast<File>()
      .fold(<String, File>{}, (result, file) {
        result[file.uri.pathSegments.last] = file;
        return result;
      });

  final missing = _expectedArtifacts.where((name) => !files.containsKey(name));
  if (missing.isNotEmpty) {
    throw StateError('Missing release artifacts: ${missing.join(', ')}');
  }

  final hashes = <String, String>{};
  for (final name in _expectedArtifacts) {
    hashes[name] = sha256.convert(await files[name]!.readAsBytes()).toString();
  }

  final output = File.fromUri(
    Platform.script.resolve('../lib/src/hook_helpers/hashes.dart'),
  );
  await output.writeAsString('''
// SHA-256 hashes generated by tool/generate_hashes.dart. Do not edit manually.

const String binaryVersion = '$version';
const String binaryReleaseTag = 'v\$binaryVersion';

const Map<String, String> binaryHashes = {
${hashes.entries.map((entry) => "  '${entry.key}': '${entry.value}',").join('\n')}
};
''');
}
