// Copyright (c) 2026 just_image contributors.
// SPDX-License-Identifier: MIT
// SHA-256 hashes generated by tool/generate_hashes.dart. Do not edit manually.

const String binaryVersion = '3.0.0';
const String binaryReleaseTag = 'v$binaryVersion';

const Map<String, String> binaryHashes = {
  'libjust_image_native-macos-arm64.dylib':
      '5028caf0d31dc8202edcb11b28bf24fc89d33df7ae72dafb0a1764df544903d9',
  'libjust_image_native-macos-x64.dylib':
      '9a4ff981eac3f57048dfbf7a17561e784e35e5306372a613889836d2deae8013',
  'libjust_image_native-ios-arm64.dylib':
      '23bcf4564d5f3eb9380b3c74d41b2eaf4c51e4eeeea16138112e450d114bc156',
  'libjust_image_native-ios-simulator-arm64.dylib':
      '91680d381a4e8f3338bb489fcaef6898c869173b3abdde4109554b8c4fc2870c',
  'libjust_image_native-ios-simulator-x64.dylib':
      '919e0f3d65ed4f791ff84921987109d1ebf0ec6908f030ac629806a7dd380e07',
  'libjust_image_native-linux-x64.so':
      'ae6cd5ceefa28aee15b63562aa1e6337aa85f7e9f21273539738d282cb27d4b9',
  'libjust_image_native-linux-arm64.so':
      '9142f686036793141fc03030f24ed1410f11e6e7a67e1e7d9ec5b9dbbc936fee',
  'just_image_native-windows-x64.dll':
      '8a54ab7a7fb5a79f542044c1a6fc06c11c03f92b893dc779afb554751313716d',
  'just_image_native-windows-arm64.dll':
      '06df9aabf7a6161644cb313752fcca94f3e175a159a50e06f557aa301da8b525',
  'libjust_image_native-android-arm64.so':
      '627245efae8867027a3c625e271dafb9848b34d2c137f92b55dbc5a506006a45',
  'libjust_image_native-android-arm.so':
      'a3329244deaae69d5cfaa73cb6dcd4cc0d872f2c4beeb2bb4c922e2b68e495ab',
  'libjust_image_native-android-x64.so':
      '99fd5af1021a8eaaee72667eb5e7bd13775c38e9e4521470fbf79dd1722699b7',
  'libjust_image_native-macos-arm64.a':
      '438e9068c7f1c4954a147af07e18cccd0a6e76dafe4e46b4f8166fd3f6a1a9f9',
  'libjust_image_native-macos-x64.a':
      '969bdb90b848c2ec1377302fcc653852dd7ad924ea5558cf0e3e2a27231ce1fb',
  'libjust_image_native-ios-arm64.a':
      '5ce0f29fb7ef6c3e0c17a217bda1fb492d5ea8435604c011ba31c3ba056afaf8',
  'libjust_image_native-ios-simulator-arm64.a':
      'f0d04087c38ad59ca78ce89f7986ca0d9b76f477af2df98d51c330d0f60f3c2b',
  'libjust_image_native-ios-simulator-x64.a':
      '840b6a5123cd1edc9072028d9fbe53d1f3fde35df04b5f02aeb034d7b86fb9e6',
  'libjust_image_native-linux-x64.a':
      'c13c8c644c4fa6bc5cf563206982e6e7081a09515789d3107dd1c61a78b8db9f',
  'libjust_image_native-linux-arm64.a':
      '2f00856931a89588c9976ec6cb0192ab6eab544b09affb20cecb03c1660a89a3',
  'just_image_native-windows-x64.lib':
      '2486e1de7ac238cbaf378a8be5e6b1ef9362fcaf7a8e86cac3f77b8dad0fc89d',
  'just_image_native-windows-arm64.lib':
      'b61c65c244ab6706172847aedbaf04ed38c0b3ec639bdfbd066551389b203343',
  'libjust_image_native-android-arm64.a':
      '1ff534d9e48c1ed75aa4eccd61fb8c103f2329003f08fd8719d9582707619ba9',
  'libjust_image_native-android-arm.a':
      'd9dc9e77b65685c3cd8b8ac2de997fe9a38ab1266ba971e7cf4862484791ea73',
  'libjust_image_native-android-x64.a':
      'ba0b90e9cbe2af9086dcbeca7eec6e9b52d8ff1e271167337f00e7b7b9312b72',
};
