// SHA-256 hashes for pre-built native libraries.
//
// These hashes are generated by CI on each release tag. If a hash does not
// match the downloaded file, the build will fail with a security error.
//
// To update: run `dart run tool/generate_hashes.dart` after a release and
// commit the result.

const String binaryVersion = '3.0.0';
const String binaryReleaseTag = 'v$binaryVersion';

const Map<String, String> binaryHashes = {
  // Dynamic libraries are used by JIT and debug commands without link hooks.
  'libjust_image_native-macos-arm64.dylib': 'PENDING',
  'libjust_image_native-macos-x64.dylib': 'PENDING',
  'libjust_image_native-ios-arm64.dylib': 'PENDING',
  'libjust_image_native-ios-simulator-arm64.dylib': 'PENDING',
  'libjust_image_native-ios-simulator-x64.dylib': 'PENDING',
  'libjust_image_native-linux-x64.so': 'PENDING',
  'libjust_image_native-linux-arm64.so': 'PENDING',
  'just_image_native-windows-x64.dll': 'PENDING',
  'just_image_native-windows-arm64.dll': 'PENDING',
  'libjust_image_native-android-arm64.so': 'PENDING',
  'libjust_image_native-android-arm.so': 'PENDING',
  'libjust_image_native-android-x64.so': 'PENDING',
  // Static libraries are consumed by the release/AOT link hook.
  // macOS
  'libjust_image_native-macos-arm64.a': 'PENDING',
  'libjust_image_native-macos-x64.a': 'PENDING',
  // iOS device and simulators are distinct build targets but keep a stable
  // library basename once bundled by Native Assets.
  'libjust_image_native-ios-arm64.a': 'PENDING',
  'libjust_image_native-ios-simulator-arm64.a': 'PENDING',
  'libjust_image_native-ios-simulator-x64.a': 'PENDING',
  // Linux
  'libjust_image_native-linux-x64.a': 'PENDING',
  'libjust_image_native-linux-arm64.a': 'PENDING',
  // Windows
  'just_image_native-windows-x64.lib': 'PENDING',
  'just_image_native-windows-arm64.lib': 'PENDING',
  // Android
  'libjust_image_native-android-arm64.a': 'PENDING',
  'libjust_image_native-android-arm.a': 'PENDING',
  'libjust_image_native-android-x64.a': 'PENDING',
};
